theme: jekyll-theme-minimal
logo: pfp.png
title: "Micaela Ae young Roth"

description: |
  <br>
  "Let the words of my mouth and the meditation of my heart be acceptable in your sight, O Lord, my rock and my redeemer" - Psalm 19:14
  
  
