theme: jekyll-theme-minimal
logo: pfp.png
title: "Micaela Ae young Roth"

description: |
  <br>
  Alive in Christ by grace alone |
  Math enthusiast |
  Psalm 19:14 |
 |
  Fun exercise: Where did the name of this site come from?
  
  
